name: Trigger auto deployment for navbaacr1

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/navbaacr1-AutoDeployTrigger-6ebbfe5b-3e8b-4925-8210-46e6a25dd530.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: navbaacr1.azurecr.io
          username: ${{ secrets.NAVBAACR1_REGISTRY_USERNAME }}
          password: ${{ secrets.NAVBAACR1_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: navbaacr1.azurecr.io/navbaacr122:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.NAVBAACR1_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n navbaacr1 -g navbaacr1 --server navbaacr1.azurecr.io --username  ${{ secrets.NAVBAACR1_REGISTRY_USERNAME }} --password ${{ secrets.NAVBAACR1_REGISTRY_PASSWORD }}
            az containerapp update -n navbaacr1 -g navbaacr1 --image navbaacr1.azurecr.io/navbaacr122:${{ github.sha }}
